title: data2comms
description: Agência de PR, influência, imprensa, pesquisa e inteligência cultural.
url: https://data2comms.com.br
baseurl: ""
permalink: /post/:title/
markdown: kramdown
future: true
timezone: America/Sao_Paulo

collections:
  metodo:
    output: true
    permalink: /metodo/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "metodo"
    values:
      layout: "metodo"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-sitemap
