title: data2comms
description: Agência de PR, pesquisa, imprensa e inteligência cultural.
url: https://rennanmetsi-gif.github.io
baseurl: /data2commsfinal
permalink: /post/:title/
markdown: kramdown
future: true
timezone: America/Sao_Paulo

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
