title: data2comms
description: Agência de PR, pesquisa, imprensa e inteligência.
url: ""
baseurl: "/data2commsfinal"
permalink: /blog/:title/
markdown: kramdown

collections_dir: .
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
