backend:
  name: github
  repo: rennanmetsi-gif/data2commsfinal
  branch: main
  base_url: https://decap-cms-oauth-provider.vercel.app # Gateway público de autenticação

media_folder: "assets/img/blog"
public_folder: "/assets/img/blog"
collections_dir: .

collections:
  - name: "posts"
    label: "Publicações"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Moda", "Beleza", "Saúde", "Tecnologia", "Comportamento"] }
      - { label: "Imagem de Capa", name: "image", widget: "image" }
      - { label: "Tempo de Leitura", name: "reading_time", widget: "string", default: "5 MIN" }
      - { label: "Resumo", name: "summary", widget: "string" }
      - { label: "Corpo do Texto", name: "body", widget: "markdown" }
